{% set name = "biobb_chemistry" %}
{% set version = "1.0.2" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "e984fa83d07416507f81a588a480e44d043904a0859921b04cda026baa7abc37" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python

requirements:
  host:
    - python ==3.6.*
    - setuptools
    - biobb_common ==0.1.4
    - openbabel ==2.4.1
  run:
    - python ==3.6.*
    - biobb_common ==0.1.4
    - openbabel ==2.4.1
test:
  imports:
    - biobb_chemistry
    - biobb_chemistry.babel
    - biobb_chemistry.acpype

about:
  home: https://github.com/bioexcel/biobb_chemistry
  license: Apache Software License
  license_family: APACHE
  license_file: ''
  summary: biobb_chemistry is the Biobb module collection to perform chemistry over molecular dynamics simulations.
  description: "biobb_chemistry is the Biobb module collection to perform chemistry over molecular dynamics simulations."
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
